<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="Lidar_radius" value="0.05" />
    <xacro:property name="Lidar_length" value="0.04" />

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius= "${Lidar_radius}" length="${Lidar_length}" />
            </geometry>
            <origin xyz="0 0 ${Lidar_length /2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius= "${Lidar_radius}" length="${Lidar_length}"/>
            </geometry>
            <origin xyz="0 0 ${Lidar_length /2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${Lidar_radius}" h="${Lidar_length}" 
                                xyz="0 0 ${Lidar_length /2.0}" rpy="0 0 0" />
    </link>

    <joint name="Laser_Base_joint" type="fixed">
        <parent link="base_link" />
        <child link="laser_frame" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
    </joint>


    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>